#!/bin/bash

name="$1"
spec=`echo "$name" | cut -c14-20`

chilo=0.2
siglo=1.7
sighi=6.0
if [ $spec = "317_024" ]; then
    sncut=6.5
    chihi=1.3
else
    sncut=5.0
    chihi=2.0
fi
echo "$name $sncut $chihi"
awk '{s+=1; if($5>siglo0&&$5<sighi0&&$9>sncut0&&$11>chilo0&&$11<chihi0) print "rf1",$13,$14,3,$1,50,s,$15,"1.7 3 3.5 0.2 5 102",$9,$11,$5,$16}' siglo0=${siglo} sighi0=${sighi} sncut0=${sncut} chilo0=${chilo} chihi0=${chihi} ${name} | sort -g +14 -15 > ${name}2
