#!/bin/bash

#. ../setup.sh

NIGHT=$1
SHOT=$2
RA=$3
DEC=$4
TRACK=$5
FP=$6
PAR=$7
CFG=../${NIGHT}v${SHOT}.config
LOG=${NIGHT}v${SHOT}.log

# Fall back to vdrp.config if no night/shot specific 
# configuration file exists.
if [ ! -f $CFG ]; then
    CFG=../vdrp.config
fi

echo Configuration file $CFG
vdrp_astrom --logfile $LOG -c $CFG $NIGHT $SHOT $RA $DEC $TRACK -t all --fplane_txt /data/00115/gebhardt/vdrp/fplane.$FP --parangle ${PAR}
